# Generated by Django 5.0.4 on 2024-04-03 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cod_proj', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('length', models.FloatField()),
                ('rooms', models.IntegerField()),
                ('project_cost', models.FloatField()),
                ('administrative_cost', models.FloatField()),
                ('visits', models.IntegerField()),
                ('id_project_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.projecttype')),
            ],
        ),
    ]
