# Generated by Django 5.0.4 on 2024-04-03 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_id_project_type_project_project_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('expected_date', models.DateField()),
                ('achieved_date', models.DateField()),
                ('status', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.milestone'),
        ),
    ]
