# Generated by Django 5.0.4 on 2024-04-04 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_team_project_team_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='team_name',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
