# Generated by Django 5.0.4 on 2024-04-04 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_apropriation_project_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apropriation',
            name='total_hour',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apropriation',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
